version: "3.8"
services:
  rstudio:
    image: bioconductor/bioconductor_docker:RELEASE_3_13
    build:
      context: dev/docker
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=pw
      - DISABLE_AUTH=false
      - RENV_PATHS_CACHE=/home/rstudio/.local/share/renv/cache
    volumes:
      - .:${PROJECT_PATH_CONTAINER:-/home/rstudio/project}
      - ${DOTFILES_ROOT:-./dev/dotfiles}:/home/rstudio/dotfiles
      - ${RENV_PATHS_CACHE_HOST:-./dev/renv/cache}:/home/rstudio/.local/share/renv/cache
      - ${GITHUB_SSH_IDENTITY:-/dev/null}:/home/rstudio/.ssh/id_github:ro
